# Generated by Django 3.1.7 on 2021-06-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='material',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
