# Generated by Django 3.1.7 on 2021-05-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='student_response',
            field=models.CharField(blank=True, default=' ', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
