# Generated by Django 3.1.7 on 2021-05-11 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='student_response',
        ),
    ]
