# Generated by Django 3.1.7 on 2021-05-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='created',
        ),
        migrations.RemoveField(
            model_name='question',
            name='created',
        ),
        migrations.AddField(
            model_name='answer',
            name='letter',
            field=models.CharField(default='', max_length=1),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
