# Generated by Django 3.1.7 on 2021-05-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210511_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='student_response',
            field=models.CharField(default='t', max_length=1),
        ),
    ]
