# Generated by Django 3.1.7 on 2021-08-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210824_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='raw_score',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='result',
            name='scaled_score',
        ),
    ]
