# Generated by Django 3.1.7 on 2021-06-29 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='passage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
