# Generated by Django 3.1.7 on 2021-05-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20210510_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='student_response',
            field=models.CharField(default='test', max_length=1),
        ),
    ]
