# Generated by Django 3.1.7 on 2021-08-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20210824_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='score',
            new_name='raw_score',
        ),
        migrations.AddField(
            model_name='result',
            name='scaled_score',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
