# Generated by Django 3.1.7 on 2021-05-11 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_question_student_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='student_response',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
