# Generated by Django 3.1.7 on 2021-05-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20210510_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='student_response',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
