# Generated by Django 3.1.7 on 2021-09-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_student_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
