# Generated by Django 3.1.7 on 2021-08-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210801_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='student_answer',
            name='answer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
