# Generated by Django 3.1.7 on 2021-05-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20210510_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='letter',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='student_response',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
