# Generated by Django 3.1.7 on 2021-04-26 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tester', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='exam',
            name='num_questions',
            field=models.IntegerField(default=0),
        ),
    ]
