# Generated by Django 3.1.7 on 2021-06-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='passage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
