# Generated by Django 3.1.7 on 2021-05-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='time',
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='url',
            field=models.SlugField(default=' ', max_length=60),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='section',
            name='time',
            field=models.IntegerField(default=5, help_text='duration of the section in minutes'),
        ),
    ]
