# Generated by Django 3.1.7 on 2021-06-07 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_section_passage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='passage',
        ),
    ]
