# Generated by Django 3.1.7 on 2021-05-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.IntegerField(help_text='duration of the exam in minutes'),
        ),
    ]
