# Generated by Django 3.1.7 on 2021-05-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20210510_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.IntegerField(help_text='duration of the exam in minutes', max_length=1000),
        ),
        migrations.AlterField(
            model_name='section',
            name='num_questions',
            field=models.IntegerField(default=0, max_length=1000),
        ),
        migrations.AlterField(
            model_name='section',
            name='time',
            field=models.IntegerField(help_text='duration of the section in minutes', max_length=1000),
        ),
    ]
