# Generated by Django 3.1.7 on 2022-09-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20220916_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='payment_status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('CANCELLED', 'Cancelled'), ('NONE', None)], default='NONE', max_length=9, null=True),
        ),
    ]
