# Generated by Django 3.1.7 on 2021-06-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_remove_section_passage'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='num_passages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
