# Generated by Django 3.1.7 on 2021-07-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_sectioninstance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectioninstance',
            name='time_remaining',
        ),
        migrations.AddField(
            model_name='sectioninstance',
            name='minutes_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sectioninstance',
            name='seconds_left',
            field=models.IntegerField(default=0),
        ),
    ]
