math_category_map = {
    'FA': 'Fundamental Algebra',
    'WP': 'Word Problems',
    'VS': 'Variable Substitution',
    'SE': 'System of Equations',
    'Q': 'Quadratics',
    'FOIL': 'Factoring and Foiling',
    'AI': 'Absolute Value/Inequalities',
    'EXP': 'Exponents',
    'GEO': 'Geometry',
    'CR': 'Circles',
    'TR': 'Triangles',
    '3D': '3D Shapes',
    'PL': 'Parallel Lines',
    'RAT': 'Ratios',
    'CN': 'Complex Numbers',
    'TRIG': 'Trigonometry',
    'RG': 'Reading Graphs',
    'PROB': 'Probability',
    'STAT': 'Statistics',
    'LOG': 'Logarithms',
    'RE': 'Rational Expressions',
    'MISC': 'Miscellaneous',
    'MMM': 'Mean, Median, Mode',
    'FN': 'Function Notation'
}