act_math_category_map = {
    'FA': 'Fundamental Algebra',
    'WP': 'Word Problems',
    # 'VS': 'Variable Substitution',
    'SE': 'System of Equations',
    'Q': 'Quadratics',
    'FOIL': 'Factoring and Foiling',
    'AI': 'Absolute Value/Inequalities',
    'EXP': 'Exponents',
    'GEO': 'Geometry',
    'CR': 'Circles',
    'TR': 'Triangles',
    #'3D': '3D Shapes',
    'PL': 'Parallel Lines',
    'RAT': 'Ratios',
    'CN': 'Complex Numbers',
    'TRIG': 'Trigonometry',
    'RG': 'Reading Graphs',
    'PROB': 'Probability',
    'STAT': 'Statistics',
    'LOG': 'Logarithms',
    'RE': 'Rational Expressions',
    'MISC': 'Miscellaneous',
    'MMM': 'Mean, Median, Mode',
    'FN': 'Function Notation'
}

sat_math_category_map = {
    'FA': 'Fundamental Algebra',
    'WP': 'Word Problems',
    # 'VS': 'Variable Substitution',
    'SE': 'System of Equations',
    'Q': 'Quadratics',
    'FOIL': 'Factoring and Foiling',
    'AI': 'Absolute Value/Inequalities',
    'EXP': 'Exponents',
    'GEO': 'Geometry',
    'CR': 'Circles',
    'TR': 'Triangles',
    #'3D': '3D Shapes',
    'PL': 'Parallel Lines',
    'RAT': 'Ratios',
    'CN': 'Complex Numbers',
    'TRIG': 'Trigonometry',
    'RG': 'Reading Graphs',
    'PROB': 'Probability',
    'STAT': 'Statistics',
    # 'LOG': 'Logarithms',
    'RE': 'Rational Expressions',
    'MISC': 'Miscellaneous',
    'MMM': 'Mean, Median, Mode',
    # 'FN': 'Function Notation'
}

sat_english_category_map = {
    'A': 'Agreement',
    'P': 'Punctuation',
    'ST': 'Sentence Structure',
    'VC': 'Vocabulary',
    'CW': 'Common Words',
    # 'ID': 'Idioms',
    'COMP': 'Comparisons',
    'PS': 'Parts of Speech',
    'R': 'Redundancy',
    'TW': 'Transition Words',
    'SP': 'Sentence Placement',
    'RG': 'Reading Graphs',
    'UP': 'Understanding Passages',
    'TS': 'Tenses',
    'SX': 'Syntax',
}

act_english_category_map = {
    'A': 'Agreement',
    'P': 'Punctuation',
    'ST': 'Sentence Structure',
    'VC': 'Vocabulary',
    'CW': 'Common Words',
    'ID': 'Idioms',
    # 'COMP': 'Comparisons',
    # 'PS': 'Parts of Speech',
    'R': 'Redundancy',
    'TW': 'Transition Words',
    'SP': 'Sentence Placement',
    # 'RG': 'Reading Graphs',
    'UP': 'Understanding Passages',
    'TS': 'Tenses',
    'SX': 'Syntax',
}